export const files = [
  ['.github', 'workflows', 'publish.yml'],
  ['.github', 'workflows', 'commitlint.yml'],
  ['.github', 'workflows', 'code-quality.yml'],
  ['.github', 'workflows', 'release.yml'],
  ['.vscode', 'settings.json'],
  ['src', 'index.ts'],
  ['src', 'math.ts'],
  ['test', 'math.spec.ts'],
  ['.editorconfig'],
  ['.eslintrc.json'],
  ['gitignore'],
  ['.mailmap'],
  ['.prettierignore'],
  ['.prettierrc'],
  ['AUTHORS'],
  ['CHANGELOG.md'],
  ['commitlint.config.js'],
  ['cspell.json'],
  ['jest.config.js'],
  ['LICENSE'],
  ['package.json'],
  ['README.md'],
  ['tsconfig.json'],
];
