#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '💬 Spell Checker,🎨 Styling then 🚀 build the application'

# if Check types passes
echo '✅ Check types passed'

# Check Code Spell
npm run check:cspell || (
  echo '🚨 cspell failed'
  false
)

# if Code Spell Passes
echo '✅ Code Spell passed'

# Check Prettier Standards
npm run check:format || (
  echo '🚨 Check Format failed'
  false
)

# if Prettier passes
echo '✅ prettier passed'

# if everything is passes... try to run build
echo '💚 Alright... Code looks good to me and tests passed.... now trying to build'
