# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish Release & Create Change Log

on:
  push:
    branches: [master]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      # Get checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'

      # Install Dependencies
      - name: Install dependencies 🔧
        run: npm ci

      # Npm Run Test
      - name: Run Test All
        run: npm run test

      # Build application
      - name: Run Build
        run: npm run build

      # Run Semantic Release
      - name: Semantic Release
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # Checkout Develop
      - name: Checkout Develop
        uses: actions/checkout@v3
        with:
          ref: develop

      # Pull From `Master` to `Develop`
      - name: Pull From `Master` to `Develop`
        run: |
          git pull origin master
          git push
